version: '3.9'
services:
  Simon:
    container_name: Simon
    image: node:18.16.0
    restart: always
    command: sh -c "yarn install && yarn dev"
    working_dir: /app
    volumes:
      - .:/app

networks:
  default:
    external:
      name: system

volumes:
  mysql-data: